### ISSUE TITLE
boosting 4-vectors does not work on TLorentzVectorArray

### ISSUE THREAD

**Issue by lukasheinrich** [scikit-hep/uproot-methods#62]
Hi,

I am stumbling over a problem w/ 4-vectors in uproot_methods:

Consider the problem of having events with lorentz vectors and wanting to boost all of them into their rest frame. The operation works per-event, but not o the full full (batched) set of events

I'm looking into what the issue could be but perhaps someone is faster

```
x = [
    [
        [0,0,12,13],
        [0,0,4,5]
    ],
    [
        [0,0,15,17],
        [0,0,24,25]
    ],
]

mom = awkward.fromiter(x)
v = uproot_methods.TLorentzVectorArray.from_cartesian(mom[:,:,0],mom[:,:,1],mom[:,:,2],mom[:,:,3])

boost_back = (v.p3/v.p3.mag)*v.beta
print(
    [vv.boost(bb) for vv,bb in zip(v,-boost_back)]
)
print(
    v.boost(-boost_back)
)
```

the first `print` works as expected, the seconds does not and fails with 

```
in boost(self, p3)
    227         gamma2 = self.awkward.numpy.zeros(b2.shape, dtype=self.awkward.numpy.float64)
    228         mask = (b2 != 0)
--> 229         gamma2[mask] = (gamma[mask] - 1) / b2[mask]
    230         del mask
    231 

IndexError: too many indices for array
```

**Comment by jpivarski** [comment]
I see what's going on here: it's a casualty of scope creep. Originally, these functions were written for Numpy arrays—the idea being that you could have flat arrays of Lorentz vectors—but in most cases, they "just worked" for awkward arrays (because they share Numpy idioms) and this fact is clearly useful. However, awkward arrays don't support masked-assignment (I'm hoping to make this possible in awkward 1.0). In most of these functions, I removed masked-assignment and in-place assignment, but I must have missed this one.

The masked-assignment is intended to protect against division by zero—specifically, zero over zero (corresponding to boosting by exactly zero). To do this truly vectorially, we should let the division by zero happen and clean up afterward. Since these are zero over zero cases, the result we want to clean up is NaN. If the array is Numpy, we can mask-assign these cases; otherwise, we can use awkward's `fillna` method (name borrowed from Pandas).

I believe that the correct limit for this case is `gamma2` → 0.5. Since you're closer to the physics of this problem, hopefully you can verify this. In fact, I don't know if we've had a customer for boosted 4-vectors yet, so checking the math would be prudent for your goals and very much appreciated for mine.

The fix is in PR #63.

**Comment by jpivarski** [comment]
I just noticed that I have an open PR (#63) that should fix this, and it's pretty stale. Did this fix your problem/is it no longer relevant/etc.?

**Comment by jrueb** [comment]
For me this problem is still relevant. I get a
`TypeError: (arrays of) TVector3 can only be added to/subtracted from other (arrays of) TVector3`
after applying the patch. It seems that this is unrelated as it arises from a few lines further down.

**Comment by roy-brener-cern** [comment]
I would like to add a simple a question about a boost which simply does not work.
I have
```
>>> mu1_LV
<PtEtaPhiMassLorentzVectorArray [PtEtaPhiMassLorentzVector(pt=4.5, eta=3.2, phi=2.1, mass=25.34)] at 0x7f6289903390>
>>> boost_vector
<ObjectArrayMethods [TVector3(-0.037353, 0.063868, 0.90606)] at 0x7f61db37c240>
```
and wish to do
`>>> mu1_LV.boost([boost_vector])
`
which does not work:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rbrener/Programs/anaconda3/envs/env_pytorch/lib/python3.6/site-packages/uproot_methods/classes/TLorentzVector.py", line 223, in boost
    raise TypeError("boost p3 must be an (array of) TVector3")
TypeError: boost p3 must be an (array of) TVector3
```
Tried everything, haven't found a solution. Help please!
